[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "server"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
hyper = "1.6.0"
tower = { version = "0.5.2", features = [] }
tower-http = { version = "0.6.6", features = [
    "trace",
    "timeout",
    "request-id",
    "cors",
    "normalize-path",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
reqwest = { version = "0.12.19", default-features = false, features = [
    "json",
    "rustls-tls",
] }
sqlx = { version = "0.8.6", features = [
    "postgres",
    "runtime-tokio-rustls",
    "macros",
    "migrate",
    "chrono",
    "json",
    "uuid",
] }

dashmap = "6.1.0"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v7", "serde"] }
dotenvy = "0.15.7"
anyhow = "1.0.98"
thiserror = "2.0.12"
async-trait = "0.1.88"
futures = "0.3"
